spring:
  application:
    name: GControl-ticket-management-service
  profiles:
    active: stag

eureka:
  instance:
    hostname: localhost
    serviceUrl:
      defaultZone : http://${eureka.instance.hostname}:8761/eureka/


