spring:
  application:
    name: GControl-ticket-management-service

server:
  port: 8289
eureka:
  instance:
    hostname: https://192.168.1.37
    serviceUrl:
      defaultZone : http://${eureka.instance.hostname}:8761/eureka/


